# Generated by Django 4.2.13 on 2024-05-21 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sliders', '0002_alter_slider_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slider',
            options={'ordering': ['my_order']},
        ),
        migrations.AddField(
            model_name='slider',
            name='my_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
